app_comments/urls.py
from django.conf.urls import url
from .views import add_comment

urlpatterns = [
    url(r'^add_comment', add_comment, name='add_comment'),
]

app_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

app_login/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'callback/$', callback, name='callback'),
    url(r'logout/$', logout, name='logout'),
]

kerja_kuy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_forum.urls as app_forum
import app_profile.urls as app_profile
import app_login.urls as app_login
import app_comments.urls as app_comments

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app_forum/', include(app_forum, namespace='app_forum')),
    url(r'^app_profile/', include(app_profile, namespace='app_profile')),
    url(r'^app_comments/', include(app_comments, namespace='app_comments')),
    url(r'^app_login/', include(app_login, namespace='app_login')),
    url(r'^$', RedirectView.as_view(
        url='/app_login/', permanent=True))
]

app_login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Company(models.Model):
    id_perusahaan = models.CharField('Id Perusahaan', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    url_photo = models.CharField('Url Photo', max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

app_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Company
from app_forum.models import Forum
from app_comments.models import Comment
from app_comments.forms import Forum_Comment
import requests

data = {}
response = {}
# Create your views here.
def index(request):
    if "id_perusahaan" in request.session:
        response['logged_in'] = "true"
        response['nama'] = request.session['name']
        response['url_photo'] = request.session['logoUrl']
    else:
        response['logged_in'] = None

    response['Forum'] = Forum.objects.all().order_by('-created_date')
    response['Comment'] = Comment.objects.all().order_by('-created_date')
    response['Forum_Comment'] = Forum_Comment
    return render(request, 'app_login.html', response)

# def auth(request):
#     url = "https://www.linkedin.com/oauth/v2/authorization"
#     params = {
#         "response_type" : "code",
#         "client_id" : "81fruveyl5xurr",
#         "redirect_uri" : "https://localhost:8000/login/callback",
#         "state" : "DCEeFWf45A53sdfKef424"
#     }

#     print(requests.get(url, params=params).text)
#     return render(request, 'login/login.html')

def callback(request):
    print("masuk sini")
    if request.method == "GET":
        code = request.GET.get('code', '')

        url = "https://www.linkedin.com/oauth/v2/accessToken"

        params = {
            "grant_type" : "authorization_code",
            "code" : str(code),
            "redirect_uri" : "http://localhost:8000/app_login/callback",
            "client_id" : "810u4iktbobjf4",
            "client_secret" : "8vd4NUXZhy9Scq76"
        }

        accessToken = requests.get(url, params=params).json()['access_token']

        params = {
            "oauth2_access_token" : accessToken,
            "format" : "json",
            "is-company-admin" : "true"
        }
        url2 = "https://api.linkedin.com/v1/companies"

        companyId = requests.get(url2, params=params).json()['values'][0]['id']

        params = {
            "oauth2_access_token" : accessToken,
            "format" : "json"
        }
        url3 = "https://api.linkedin.com/v1/companies/"+str(companyId)+":(id,name,company-type,website-url,logo-url,specialties)"

        jr = requests.get(url3, params=params).json()

        id_perusahaan = jr['id']
        tipePerusahaan = jr['companyType']['name']
        logoUrl = jr["logoUrl"]
        name = jr["name"]
        specialties = jr["specialties"]["values"]
        print(type(specialties))
        websiteUrl = jr["websiteUrl"]

        # request.session["id_perusahaan"] = id_perusahaan
        # request.session["name"] = name
        # request.session["logoUrl"] = logoUrl
        # request.session["tipePerusahaan"] = tipePerusahaan
        # request.session["specialties"] = specialties
        # request.session["websiteUrl"] = websiteUrl

        data = {}

        data["id_perusahaan"] = id_perusahaan
        data["name"] = name
        data["logoUrl"] = logoUrl
        data["tipePerusahaan"] = tipePerusahaan
        data["specialties"] = specialties
        data["websiteUrl"] = websiteUrl

        set_company(request, data)

        return HttpResponseRedirect(reverse('app_profile:showProfile'))
    else:
        return HttpResponseRedirect(reverse('app_login:index'))


def set_company(request, data):
    try:
        company = Company.objects.get(id_perusahaan=data['id_perusahaan'])
    except Exception as e:
        company = Company()
        company.id_perusahaan = data['id_perusahaan']
        company.nama = data['name']
        company.url_photo = data['logoUrl']
        company.save()

    request.session["id_perusahaan"] = data['id_perusahaan']
    request.session["name"] = data['name']
    request.session["logoUrl"] = data['logoUrl']
    request.session["tipePerusahaan"] = data['tipePerusahaan']
    request.session["specialties"] = data['specialties']
    request.session["websiteUrl"] = data['websiteUrl']

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('app_login:index'))

app_login/templates/app_login.html
{% extends "kerja-kuy/layout/base.html" %}
{% load staticfiles%}

{% block style %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="jumbotron" style="background-color: #1B9595">
    <h1 class="text-center" style="color: white">KerjaKuy!</h1>
    <p class="text-center" style="color: white">Platform untuk mencari pekerjaan.</p>
  </div>
</div>

<div class="container">
  <div id="login-buttons">
    {% if not logged_in %}
      <div class="col-sm-3"></div>
      <div class="col-sm-2">
        <a href="" class="btn btn-warning" style="float: right">SSO</a>
      </div>
      <div class="col-sm-2"></div>
      <div class="col-sm-2">
        <a href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=810u4iktbobjf4&redirect_uri=http://localhost:8000/app_login/callback&state=987654321" class="btn btn-primary" style="float: left;">LinkedIn</a>
      </div>
      <div class="col-sm-3"></div>
    {% endif %}
  </div>
</div>

<div class="container">
  <div id="forum-list">
    {% if Forum %}
      {% for forum in Forum %}
        <div id = "forum post">
          <h3>{{forum.perusahaan.nama}}</h3>
          <h3> {{ forum.lowongan }}</h3>
          <a style= "float: right;" id = "response{{forum.id}}" class= "btn btn-danger" onclick="test('{{ forum.id }}')"> Response</a>
          <h5> {{ forum.created_date}}</h5>
            <div id="form{{forum.id}}" style="display:none" class="container">
              <form id="form" method="POST" action="{% url 'app_comments:add_comment' %}">
                <input type="hidden" name="id_forum" value={{forum.id}}>
                <h2>Tambah Tanggapan</h2>
                {% csrf_token %}
                {{ Forum_Comment }}
                <br>
                <input id="submit" type="submit"  class="btn btn-primary" value="Submit" onclick="">
                <br>
              </form>
            </div>
          <hr>
        </div>
        <div id="comments">
          {% if Comment %}
            {% for comment in Comment %}
              {% if comment.forum.id == forum.id %}
                <div class="container">
                  {% if logged_in %}
                    <img src="{{url_photo}}" style="width:25px;height:25px;float: right">
                    <p style="float: right">"{{comment.comment}}" - {{nama}}  </p>
                  {% else %}
                    <p style="float: right">"{{comment.comment}}" - Anonymous</p>
                  {% endif %}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

{% block javascript%}
<script>
  function test (id) {
    var response = "#response"+id;
    var comments = "#form"+id;
    console.log(response);
    console.log(comments);
    $(response).remove();
    $(comments).css("display", "block");
  }
</script>
{% endblock %}

app_login/templates/company.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="login">
    <meta name="author" content="R">
    <title>{{ name }}</title>
</head>

<body>
    <img src="{{ logoUrl }}" alt="">
    <p>{{ name }}</p>
    <p>{{ id_perusahaan }}</p>
    <p>{{ tipePerusahaan }}</p>
    <ul>
    {% for i in specialties %}
        <li>{{ i }}</li>
    {% endfor %}
    </ul>
    <p>{{ websiteUrl }}</p>
</body>
</html>