app_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', show_profile, name='showProfile'),
]

kerja_kuy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_forum.urls as app_forum
import app_profile.urls as app_profile
import app_login.urls as app_login
import app_comments.urls as app_comments

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app_forum/', include(app_forum, namespace='app_forum')),
    url(r'^app_profile/', include(app_profile, namespace='app_profile')),
    url(r'^app_comments/', include(app_comments, namespace='app_comments')),
    url(r'^app_login/', include(app_login, namespace='app_login')),
    url(r'^$', RedirectView.as_view(
        url='/app_login/', permanent=True))
]

app_forum/models.py
from django.db import models
from app_login.models import Company

class Forum(models.Model):
    perusahaan = models.ForeignKey(Company, null=True)
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_forum/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'cols': 100,
        'rows': 4,
        'class': 'todo-form-textarea form-control',
        'placeholder':'Masukan lowongan pekerjaan...'
        
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

app_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Forum_Lowongan
from .models import Forum
from app_login.models import Company
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse


# Create your views here.
response = {}
def index(request): # pragma: no cover
    if "id_perusahaan" in request.session:
        response['logged_in'] = "true"
        response['nama'] = request.session['name']
    else:
        return HttpResponseRedirect(reverse('app_login:index'))
    response['author'] = "Kezia Irene"

    forum = Forum.objects.all().order_by('-created_date')

    #pagination
    paginator = Paginator(forum, 3)
    page = request.GET.get('page')
    try:
        halaman = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        halaman = paginator.page(1)

    response['Forum'] = halaman
    html = 'app_forum/app_forum.html'
    response['Forum_Lowongan'] = Forum_Lowongan
    return render(request, html, response)

def add_forum(request): # pragma: no cover
    form = Forum_Lowongan(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['lowongan']
        forum = Forum(lowongan=response['lowongan'], perusahaan = Company.objects.get(id_perusahaan=request.session['id_perusahaan']))
        forum.save()
        return HttpResponseRedirect('/app_forum/')
    else:
        return HttpResponseRedirect('/app_forum/')

app_forum/templates/app_forum/app_forum.html
{% extends "kerja-kuy/layout/base.html" %}
{% load staticfiles%}

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/app_forum.css' %}">
{% endblock %}


{% block content %}
<div id="snow">
<section>
    <h1 class="forum-list-title"> Forum Lowongan Kerja</h1>
    <div class="container" id ="forum_list">
            {% if Forum %}
                {% for forum in Forum %}
                <div id ="nama_company">
                    <a href="{% url 'app_profile:showProfile' %}">
                    <span class="badge badge-pill badge-primary" id="bege">
                    <h2><p style="text-align:left"><b>{{forum.perusahaan.nama}}</b></p></h2>
                    </span></a>
                </div>
                <br>
                <div id ="picture_company">
                    <p align ="left">
                    <img src="{{forum.perusahaan.url_photo}}" style="width:60px;height:60px;float: left">
                    </p>
                </div>

                <div id = "forum post">
                    <div id = "comments">
                    <h3> {{ forum.lowongan }}</h3>
                     
                    <h5> {{ forum.created_date}}</h5>
                    </div> 
                    <hr>
                </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Maaf!</strong> Tidak ada forum
            </div>
            {% endif %}
        </div>


<div class="pagination">
    <span class="step-links"><center>
        {% if Forum.has_previous %}
            <a href="?page={{ Forum.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ Forum.number }} of {{ Forum.paginator.num_pages }}.
        </span>

        {% if Forum.has_next %}
            <a href="?page={{ Forum.next_page_number }}">next</a>
        {% endif %}
    </center>
    </span>
</div>
</section>

    <div id="myDiv">
    <input id="new_forum" class="btn btn-lg btn-block btn-info" value="Tambah Forum Lowongan" onclick="show()">
    </div>

    <div id="form" style="display:none" class="container">
      <form id="form" method="POST" action="{% url 'app_forum:add_forum' %}">
          <h2>Tambah Forum Lowongan Kerja</h2>
          {% csrf_token %}
          {{ Forum_Lowongan }}
          <br>
          <input id="submit" type="submit"  class="btn btn-primary" value="Submit" onclick="add()">
          <br>
      </form>
    </div>
</div>

    {% block javascript%}
    <script>
    function show(){

        var x = document.getElementById("form");

        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').hide();

        }

    function add(){
        var x = document.getElementById("form");

        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').show();
    }

    function test(id) {
        $("#comments").append("ntar disini form dengan ID " + id);
        $('#response').hide();
    }
    </script>
    {% endblock %}
    {% endblock %}