app_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', show_profile, name='showProfile'),
]

kerja_kuy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_forum.urls as app_forum
import app_profile.urls as app_profile
import app_login.urls as app_login
import app_comments.urls as app_comments

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app_forum/', include(app_forum, namespace='app_forum')),
    url(r'^app_profile/', include(app_profile, namespace='app_profile')),
    url(r'^app_comments/', include(app_comments, namespace='app_comments')),
    url(r'^app_login/', include(app_login, namespace='app_login')),
    url(r'^$', RedirectView.as_view(
        url='/app_login/', permanent=True))
]

templates/kerja-kuy/partials/footer.html
{% load staticfiles %} {% load static %}
<div class="footer">
    <p>Made by &copy; {{author}}</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</script>

templates/kerja-kuy/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %} {% load static %}

<nav class="navbar navbar-default navbar-static-top">
      <div class="containers">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'app_login:index' %}">Dashboard</a></li>
            <li><a href="{% url 'app_forum:index' %}">Forum</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if logged_in %}
            <li><a href="{% url 'app_profile:showProfile' %}">Hello, {{ nama }}!</a></li>
            <li><a href="/app_login/logout" onclick="return confirm('Keluar?')">Logout (Session)</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>